### ISSUE TITLE
Does Not Work With Zygist

### ISSUE THREAD

**Issue by ThePieMonster** [vietlizi/phone-is-encrypted#1]
This module seems to work without Zygist enabled. When you enable Magisk Zygist or ZygistNext this module seems to break.

Magisk (27008) [One Plus 7 Pro Android 10]

**Comment by vietlizi** [comment]
This script simply modifies the system property _ro.crypto.state_ to **encrypted**; however, the Zygisk framework changes the system's behavior to prevent the property alteration or module functionality from operating as anticipated.
